### ISSUE TITLE
derivative of RealPart is missing/ not working

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#1317]
When defining an operator that should deal with complex values, one may need the derivative of the RealPart operator. But this does not seem to work. Below is a minimal example and the same issue also holds for ImagPart:

`import odl

space = odl.uniform_discr([-1, -1], [1,1], (500,500), dtype='complex')
    
x = space.one()

realPart_op = odl.operator.default_ops.RealPart(space)
realPart_op.derivative(x)`

**Comment by adler-j** [comment]
The operator has no formal derivative (try scaling with a complex number), what would you want it to be if we implemented it?

**Comment by ozanoktem** [comment]
Agree with @adler-j , the real-part operator is not differentiable.

**Comment by kohr-h** [comment]
Well, not quite. I'd say formally, you could very well define a derivative in the Gateaux sense by identifying C with R^2 as usual. In that case, the `RealPart` operator is the same as a component projection, and it is its own derivative. However, it would still not be linear, so it's not Frechet differentiable.

So if we want, we can implement `derivative` as returning `self`, a non-linear operator, which would be okay with math.

**Comment by ozanoktem** [comment]
Well, this is where it gets tricky. Which notion of derivative is one to use, the C-linear one or the R^2-linear one? The complex plane C coincides with R^2 by the usual identification of a complex number z= x+iy, x= Rez, y= Im z, with the vector (x,y). As such it has two vector space structures, one as a two-dimensional vector space over R and the other as a one-dimensional vector space over C. The relations between them lead to the classical Cauchy-Riemann equations.

**Comment by kohr-h** [comment]
> Which notion of derivative is one to use, the C-linear one or the R^2-linear one?

I was arguing for one that isn't linear at all :-)

**Comment by kohr-h** [comment]
Adding to that, `RealPart` already implements `adjoint` that takes the R^2 perspective. The Fourier transform behaves similarly, see [here](https://odlgroup.github.io/odl/math/trafos/fourier_transform.html#adjoint-operator) for reference.

**Comment by ozanoktem** [comment]
Ok, so then I guess we should state in the documentation of `RealPart`, `ImagPart` (and perhaps also in `ComplexEmbedding`) that the adjoint for these are in the R^2 sense. Any notion of derivative should then be consistent with that view.

**Comment by ozanoktem** [comment]
Well, there is really no "issue" other than a mathematical one. If we are to consider derivatives in C as derivatives in R^2, then there is something to be done. Otherwise, the stated operators are simply not (complex) differentiable.

**Comment by kohr-h** [comment]
Well, as I wrote above I think there is a notion of derivative that does makes sense mathematically and is consistent with the rest of the library. So I think we should implement that.

Ah, what the heck, I'll do it now.
